sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t perde-app -f Dockerfile.dev .

script:
  - docker run -e CI=true perde-app npm run test -- --coverage

deploy:
  provider: "elasticbeanstalk"
  edge: true  
  region: ap-northeast-2
  app: "perde-app"
  env: "Perdeapp-env"
  #s3 bucket name
  bucket_name: "elasticbeanstalk-ap-northeast-2-868868105836"
  bucket_path: "perde-app"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key_id: $AWS_SECRET_ACCESS_KEY

after_success:
  - echo "Test Success"