sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t perde-app -f Dockerfile.dev .

script:
  - docker run -e CI=true perde-app npm run test -- --coverage

after_success:
  - echo "Test Success"